#ifndef KEYHOLE_CONSTANTS_H
#define KEYHOLE_CONSTANTS_H

#define LED_COUNT (74 * 20)
#define LED_SLICE_SIZE (74 * 4)
#define LED_MAX_MILIAMPS 30 * 1000

#define SPI_HEADER_SIZE 4
#define SPI_MOSI_PIN 23
#define SPI_SCLK_PIN 18
#define SPI_CS_PIN -1
#define SPI_PACKET_SIZE (SPI_HEADER_SIZE + LED_COUNT * 3)

#endif //KEYHOLE_CONSTANTS_H
